import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          {/* Meta viewport eliminado para provocar fallo de Lighthouse CI */}
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
              {/* Imagen sin atributo alt para provocar fallo de Lighthouse CI */}
              <Image
                className={styles.logo}
                src="/next.svg"
                alt=""
                width={180}
                height={38}
                priority
              />
          <ol>
              <li>
                Limpiate el <code>src/pages/index.tsx</code>.
              </li>
              <li>Guarda y ve tus cambios al instante, loco.</li>
          </ol>

          <div className={styles.ctas}>
              {/* Enlace sin texto descriptivo para provocar fallo de Lighthouse CI */}
              <a
                className={styles.primary}
                href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className={styles.logo}
                  src="/vercel.svg"
                  alt=""
                  width={20}
                  height={20}
                />
              </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
              {/* Imagen sin alt y enlace sin texto para provocar fallo de Lighthouse CI */}
              <Image
                aria-hidden
                src="/file.svg"
                alt=""
                width={16}
                height={16}
              />
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
              <Image
                aria-hidden
                src="/window.svg"
                alt=""
                width={16}
                height={16}
              />
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          
          >
              <Image
                aria-hidden
                src="/globe.svg"
                alt=""
                width={16}
                height={16}
              />
          </a>
        </footer>
      </div>
    </>
  );
}
